In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
import re
from nltk.corpus import stopwords
import nltk
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')
import pandas as pd
import re
import string
from textblob import TextBlob, Word, Blobber
import nltk
from nltk.corpus import stopwords
# print(stopwords.words('english'))
import plotly.express as px
from nltk.stem import WordNetLemmatizer 
from tensorflow.keras.preprocessing.text import one_hot
nltk.download('stopwords')
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from sklearn.model_selection import GridSearchCV, cross_val_score, RepeatedStratifiedKFold, RandomizedSearchCV, LeavePOut, StratifiedKFold
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, ExtraTreesClassifier, RandomForestClassifier, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression, PassiveAggressiveClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/MyDrive/NLP/NLP project/train.csv')

In [ ]:
df = df.dropna()
df = df.sample(frac=1).reset_index(drop=True)

In [4]:
from tqdm.notebook import tqdm, trange
from nltk.stem import PorterStemmer
!pip install autocorrect
from autocorrect import Speller
from autocorrect import Speller

spell = Speller(lang='en')

porter = PorterStemmer()
from nltk.tokenize import sent_tokenize, word_tokenize
def lower_text(text):
    return text.lower()

def stemSentence(sentence):
    token_words=word_tokenize(sentence)
    token_words
    stem_sentence=[]
    for word in token_words:
        stem_sentence.append(porter.stem(word))
        stem_sentence.append(" ")
    return "".join(stem_sentence)

def lemmatization(text):
    lemmatizer = WordNetLemmatizer()
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

def remove_numbers(text):
    text_cleaned = re.sub('[^a-zA-Z]',' ',text)
    return text_cleaned

def remove_stopwords(text):
    stoplist = stopwords.words('english')
    sps = stoplist
    return " ".join([word for word in str(text).split() if word not in sps])

def autospell(text):
    return " ".join([spell(word) for word in text.split()])

corpus=[]
def get_corpus(sentence):
    cps = []
    token_words=word_tokenize(sentence)
    for word in token_words:
        corpus.append(word)
    return sentence

def return_corpus(all_sentences):
    corpus=[]
    for sentence in all_sentences:
        token_words=word_tokenize(sentence)
        corpus.extend(token_words)
    return corpus

     |████████████████████████████████| 622 kB 4.4 MB/s 
  Created wheel for autocorrect: filename=autocorrect-2.6.0-py3-none-any.whl size=622249 sha256=f95493b0f01bda1b7cf486fef1f2ea7abfdc9c65768fd53d7cecbd17ce7c2486
  Stored in directory: /root/.cache/pip/wheels/fa/ce/aa/bc894efbe0541ce91dea21561d01d319783986d9787a8e9f58
Successfully built autocorrect


In [ ]:
df['text'] = df['text'].apply(remove_stopwords)
# df['title'] = df['title'].apply(remove_stopwords)
# df['author'] = df['author'].apply(remove_stopwords)

df['text'] = df['text'].apply(remove_numbers)
# df['title'] = df['title'].apply(remove_numbers)
# df['author'] = df['author'].apply(remove_numbers)

df['text'] = df['text'].apply(lemmatization)
# df['title'] = df['title'].apply(lemmatization)
# df['author'] = df['author'].apply(lemmatization)

df['text'] = df['text'].apply(lower_text)
# df['title'] = df['title'].apply(lower_text)
# df['author'] = df['author'].apply(lower_text)

# df['text'] = df['text'].apply(get_corpus)
# df['title'] = df['title'].apply(get_corpus)
# df['author'] = df['author'].apply(get_corpus)
# corpus = set(corpus)

In [ ]:
X = df['text']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
X_train = X_train.sample(frac=1).reset_index(drop=True)
X_test = X_test.sample(frac=1).reset_index(drop=True)

In [ ]:
import gensim.downloader as api
def create_glove_embedding():
    embeddings_dict = {}
    with open("/content/drive/MyDrive/NLP/NLP project/PretrainedModels/glove.6B.300d.txt", 'r', encoding="utf-8") as f:

        for line in f:
            values = line.split()
            word = values[0]
            vector = np.asarray(values[1:], "float32")
            embeddings_dict[word] = vector
    return embeddings_dict
def get_embs_vocab(model, corpus):
    embeddings = {}
    for word in corpus:
        word = word.lower()
        try:
            embeddings[word] = model[word]
        except:
            words = list(gensim.utils.tokenize(word))
            try:
                embs = [model[i] for i in words]
                emb = sum(embs)
                if emb ==0:
                    embeddings[word] = np.zeros(sh)
                else:
                    embeddings[word] = emb
            except:
                embeddings[word] = np.zeros(vec_king.shape)
    return embeddings

In [ ]:
train_corpus = return_corpus(X_train)
test_corpus = return_corpus(X_test)
train_corpus = set(train_corpus)
test_corpus = set(test_corpus)
len(train_corpus), len(test_corpus)

(121667, 61138)

In [ ]:
import gensim
from gensim.models import Word2Vec

In [ ]:
#glove embeddings
glove_embedding_model = create_glove_embedding()
vec_king = glove_embedding_model["king"]
sh = list(glove_embedding_model.values())[0].shape

train_glove_embeddings = get_embs_vocab(glove_embedding_model, train_corpus)
test_glove_embeddings = get_embs_vocab(glove_embedding_model, test_corpus)

len(test_glove_embeddings), len(train_glove_embeddings)

(61138, 121667)

In [ ]:
maxlen = 0
for sentence in X_train:
    token_words=word_tokenize(sentence)
    if len(token_words)>maxlen:
        maxlen = len(token_words)
maxlen

In [ ]:
paddinglen = 200

In [ ]:
train_embed = []
for sentence in X_train:
    token_words=word_tokenize(sentence)
    if len(token_words)<paddinglen:
        tobeadded = [np.zeros(sh)]*(paddinglen-len(token_words))
        # print(len(tobeadded), tobeadded[0].shape)
        sentence_embed = [train_glove_embeddings[word] for word in token_words]
        sentence_embed.extend(tobeadded)
    else:
        token_words=token_words[:paddinglen]
        sentence_embed = [train_glove_embeddings[word] for word in token_words]
    train_embed.append(sentence_embed)
train_embed = np.asarray(train_embed)

In [ ]:
test_embed = []
for sentence in X_test:
    token_words=word_tokenize(sentence)
    if len(token_words)<paddinglen:
        tobeadded = [np.zeros(sh)]*(paddinglen-len(token_words))
        # print(len(tobeadded), tobeadded[0].shape)
        sentence_embed = [test_glove_embeddings[word] for word in token_words]
        sentence_embed.extend(tobeadded)
    else:
        token_words=token_words[:paddinglen]
        sentence_embed = [test_glove_embeddings[word] for word in token_words]
    test_embed.append(sentence_embed)
test_embed = np.asarray(test_embed)

In [ ]:
train_embed.shape, test_embed.shape

((14628, 200, 300), (3657, 200, 300))

In [ ]:
X_train = train_embed.reshape(train_embed.shape[0], train_embed.shape[1]*train_embed.shape[2])
X_test = test_embed.reshape(test_embed.shape[0], test_embed.shape[1]*test_embed.shape[2])
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((14628, 60000), (3657, 60000), (14628,), (3657,))

In [ ]:
np.save( "/content/drive/MyDrive/NLP/NLP project/train_x.npy", X_train)
np.save( "/content/drive/MyDrive/NLP/NLP project/test_x.npy", X_test)
np.save( "/content/drive/MyDrive/NLP/NLP project/train_y.npy", y_train)
np.save( "/content/drive/MyDrive/NLP/NLP project/test_y.npy", y_test)

In [ ]:
X_train = np.load( "/content/drive/MyDrive/NLP/NLP project/train_x.npy")
X_test = np.load( "/content/drive/MyDrive/NLP/NLP project/test_x.npy")
y_train = np.load( "/content/drive/MyDrive/NLP/NLP project/train_y.npy")
y_test = np.load( "/content/drive/MyDrive/NLP/NLP project/test_y.npy")

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((14628, 60000), (3657, 60000), (14628,), (3657,))

In [ ]:
from sklearn.pipeline import make_pipeline
clf = make_pipeline(SVC(gamma='auto'))
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

print('------------------------------')


In [ ]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

In [ ]:
clf = LogisticRegression()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression



accuracy:   0.505
              precision    recall  f1-score   support

           0       0.56      0.61      0.58      2062
           1       0.42      0.37      0.40      1595

    accuracy                           0.51      3657
   macro avg       0.49      0.49      0.49      3657
weighted avg       0.50      0.51      0.50      3657

confusion matrix:
[[1255  807]
 [1002  593]]


In [ ]:
clf = AdaBoostClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy:   0.546
              precision    recall  f1-score   support

           0       0.57      0.82      0.67      2076
           1       0.44      0.18      0.26      1581

    accuracy                           0.55      3657
   macro avg       0.51      0.50      0.47      3657
weighted avg       0.51      0.55      0.49      3657

confusion matrix:
[[1707  369]
 [1290  291]]


In [ ]:
clf = MLPClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy:   0.517
              precision    recall  f1-score   support

           0       0.56      0.68      0.61      2062
           1       0.42      0.30      0.35      1595

    accuracy                           0.52      3657
   macro avg       0.49      0.49      0.48      3657
weighted avg       0.50      0.52      0.50      3657

confusion matrix:
[[1408  654]
 [1114  481]]


In [ ]:
clf = GradientBoostingClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

In [ ]:
clf = PassiveAggressiveClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy:   0.497
              precision    recall  f1-score   support

           0       0.56      0.52      0.54      2062
           1       0.43      0.47      0.45      1595

    accuracy                           0.50      3657
   macro avg       0.49      0.49      0.49      3657
weighted avg       0.50      0.50      0.50      3657

confusion matrix:
[[1072  990]
 [ 851  744]]


LSTM on tokenised text

In [ ]:
max_features=4500

In [ ]:
from nltk.tokenize import sent_tokenize,word_tokenize
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
X = df['text']

In [ ]:
tokenizer = Tokenizer(num_words = max_features, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower = True, split = ' ')
tokenizer.fit_on_texts(texts = X)
X = tokenizer.texts_to_sequences(texts = X)

In [ ]:
X = pad_sequences(sequences = X, maxlen = max_features, padding = 'pre')

In [ ]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
lstm_model = Sequential(name = 'lstm_nn_model')
lstm_model.add(layer = Embedding(input_dim = max_features, output_dim = 120, name = '1st_layer'))
lstm_model.add(layer = LSTM(units = 120, dropout = 0.2, recurrent_dropout = 0.2, name = '2nd_layer'))
lstm_model.add(layer = Dropout(rate = 0.5, name = '3rd_layer'))
lstm_model.add(layer = Dense(units = 120,  activation = 'relu', name = '4th_layer'))
lstm_model.add(layer = Dropout(rate = 0.5, name = '5th_layer'))
lstm_model.add(layer = Dense(units = len(set(y)),  activation = 'sigmoid', name = 'output_layer'))
# compiling the model
lstm_model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
lstm_model_fit = lstm_model.fit(X_train1, y_train1, epochs = 1)

 83/383 [=====>........................] - ETA: 1:12:41 - loss: 0.5508 - accuracy: 0.6962

In [ ]:
y_pred = lstm_model_fit.predict(X_test1)
score1 = metrics.accuracy_score(y_test1, y_pred)
print("accuracy:   %0.3f" % score1)
print(metrics.classification_report(y_test1, y_pred))
print("confusion matrix:")
print(metrics.confusion_matrix(y_test1, y_pred))

GRU

In [ ]:
gru_model = Sequential(name = 'gru_nn_model')
gru_model.add(layer = Embedding(input_dim = max_features, output_dim = 120, name = '1st_layer'))
gru_model.add(layer = GRU(units = 120, dropout = 0.2, 
                          recurrent_dropout = 0.2, recurrent_activation = 'relu', 
                          activation = 'relu', name = '2nd_layer'))
gru_model.add(layer = Dropout(rate = 0.4, name = '3rd_layer'))
gru_model.add(layer = Dense(units = 120, activation = 'relu', name = '4th_layer'))
gru_model.add(layer = Dropout(rate = 0.2, name = '5th_layer'))
gru_model.add(layer = Dense(units = len(set(y)), activation = 'softmax', name = 'output_layer'))
# compiling the model
gru_model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
gru = gru_model.fit(X_train, y_train, epochs = 1)

In [ ]:
y_pred = gru.predict(X_test)
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)
print(metrics.classification_report(y_test, y_pred))
print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))