In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
import re
from nltk.corpus import stopwords
import nltk
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')
import pandas as pd
import re
import string
from textblob import TextBlob, Word, Blobber
import nltk
from nltk.corpus import stopwords
# print(stopwords.words('english'))
import plotly.express as px
from nltk.stem import WordNetLemmatizer 
from tensorflow.keras.preprocessing.text import one_hot
nltk.download('stopwords')
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from sklearn.model_selection import GridSearchCV, cross_val_score, RepeatedStratifiedKFold, RandomizedSearchCV, LeavePOut, StratifiedKFold
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, ExtraTreesClassifier, RandomForestClassifier, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression, PassiveAggressiveClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/NLP/NLP project/train.csv')

In [ ]:
df = df.dropna()
df = df.sample(frac=1).reset_index(drop=True)

In [ ]:
from tqdm.notebook import tqdm, trange
from nltk.stem import PorterStemmer
!pip install autocorrect
from autocorrect import Speller
from autocorrect import Speller

spell = Speller(lang='en')

porter = PorterStemmer()
from nltk.tokenize import sent_tokenize, word_tokenize
def lower_text(text):
    return text.lower()

def stemSentence(sentence):
    token_words=word_tokenize(sentence)
    token_words
    stem_sentence=[]
    for word in token_words:
        stem_sentence.append(porter.stem(word))
        stem_sentence.append(" ")
    return "".join(stem_sentence)

def lemmatization(text):
    lemmatizer = WordNetLemmatizer()
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

def remove_numbers(text):
    text_cleaned = re.sub('[^a-zA-Z]',' ',text)
    return text_cleaned

def remove_stopwords(text):
    stoplist = stopwords.words('english')
    sps = stoplist
    return " ".join([word for word in str(text).split() if word not in sps])

def autospell(text):
    return " ".join([spell(word) for word in text.split()])

corpus=[]
def get_corpus(sentence):
    cps = []
    token_words=word_tokenize(sentence)
    for word in token_words:
        corpus.append(word)
    return sentence
    

     |████████████████████████████████| 622 kB 11.6 MB/s 
  Created wheel for autocorrect: filename=autocorrect-2.6.0-py3-none-any.whl size=622249 sha256=4853dcefd799e837aba3f5ee53c463bf739bf44dcea21c6984f26ec97d67652c
  Stored in directory: /root/.cache/pip/wheels/fa/ce/aa/bc894efbe0541ce91dea21561d01d319783986d9787a8e9f58
Successfully built autocorrect


In [ ]:
df['text'] = df['text'].apply(remove_stopwords)
# df['title'] = df['title'].apply(remove_stopwords)
# df['author'] = df['author'].apply(remove_stopwords)

df['text'] = df['text'].apply(remove_numbers)
# df['title'] = df['title'].apply(remove_numbers)
# df['author'] = df['author'].apply(remove_numbers)

df['text'] = df['text'].apply(lemmatization)
# df['title'] = df['title'].apply(lemmatization)
# df['author'] = df['author'].apply(lemmatization)

df['text'] = df['text'].apply(lower_text)
# df['title'] = df['title'].apply(lower_text)
# df['author'] = df['author'].apply(lower_text)

# df['text'] = df['text'].apply(get_corpus)
# df['title'] = df['title'].apply(get_corpus)
# df['author'] = df['author'].apply(get_corpus)
# corpus = set(corpus)

In [ ]:
# dropping length 0, 1, 2 texts
ohr = []
for index in range(len(df)):
    # ohr.append(len(onehot_rep_test[index]))
    if len(df['text'][index])==0 or len(df['text'][index])==1 or len(df['text'][index])==2:
        ohr.append(index)
print(len(ohr), len(df))
df = df.drop(ohr)        
df = df.sample(frac=1).reset_index(drop=True)
print(len(df))

93 18285
18192


-------------------------------Preprocessing ends----------------------------------------

In [ ]:
X = df['text']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
X_train = X_train.sample(frac=1).reset_index(drop=True)
X_test = X_test.sample(frac=1).reset_index(drop=True)

In [ ]:
voc_size = 5000
onehot_rep = [one_hot(sentence,voc_size)for sentence in X_train]
onehot_rep_test = [one_hot(sentence,voc_size)for sentence in X_test]

In [ ]:
len(onehot_rep), len(onehot_rep[0]), len(onehot_rep[1])

(14553, 188, 1020)

In [ ]:
maxlen = 386

In [ ]:
one_hot_embeddings_train = pad_sequences(onehot_rep,padding='pre',maxlen=maxlen)
one_hot_embeddings_test = pad_sequences(onehot_rep_test,padding='pre',maxlen=maxlen)

In [ ]:
len(one_hot_embeddings_train), len(one_hot_embeddings_train[0]), len(one_hot_embeddings_train[1])

(14553, 386, 386)

-----------------vectorization (OneHot) ends -----------------

In [ ]:
X_train = one_hot_embeddings_train
X_test = one_hot_embeddings_test

In [ ]:
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train, y_train)

y_pred = naive_bayes_classifier.predict(X_test)

score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

print('------------------------------')


accuracy:   0.513
              precision    recall  f1-score   support

           0       0.57      0.54      0.56      2076
           1       0.44      0.47      0.46      1581

    accuracy                           0.51      3657
   macro avg       0.51      0.51      0.51      3657
weighted avg       0.52      0.51      0.51      3657

confusion matrix:
[[1131  945]
 [ 836  745]]
------------------------------


In [ ]:
from sklearn.pipeline import make_pipeline
clf = make_pipeline(SVC(gamma='auto', probability=True))
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

print('------------------------------')


accuracy:   0.561
              precision    recall  f1-score   support

           0       0.56      0.99      0.72      2052
           1       0.37      0.01      0.02      1587

    accuracy                           0.56      3639
   macro avg       0.47      0.50      0.37      3639
weighted avg       0.48      0.56      0.41      3639

confusion matrix:
[[2028   24]
 [1573   14]]
------------------------------


In [ ]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy:   0.513
              precision    recall  f1-score   support

           0       0.57      0.57      0.57      2052
           1       0.44      0.44      0.44      1587

    accuracy                           0.51      3639
   macro avg       0.50      0.50      0.50      3639
weighted avg       0.51      0.51      0.51      3639

confusion matrix:
[[1168  884]
 [ 888  699]]


In [ ]:
clf = LogisticRegression()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy:   0.545
              precision    recall  f1-score   support

           0       0.58      0.80      0.67      2104
           1       0.42      0.20      0.27      1535

    accuracy                           0.54      3639
   macro avg       0.50      0.50      0.47      3639
weighted avg       0.51      0.54      0.50      3639

confusion matrix:
[[1677  427]
 [1230  305]]


In [ ]:
clf = AdaBoostClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy:   0.555
              precision    recall  f1-score   support

           0       0.58      0.82      0.68      2104
           1       0.44      0.19      0.26      1535

    accuracy                           0.55      3639
   macro avg       0.51      0.51      0.47      3639
weighted avg       0.52      0.55      0.51      3639

confusion matrix:
[[1727  377]
 [1243  292]]


In [ ]:
clf = MLPClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy:   0.539
              precision    recall  f1-score   support

           0       0.59      0.66      0.62      2104
           1       0.45      0.38      0.41      1535

    accuracy                           0.54      3639
   macro avg       0.52      0.52      0.52      3639
weighted avg       0.53      0.54      0.53      3639

confusion matrix:
[[1383  721]
 [ 955  580]]


In [ ]:
clf = GradientBoostingClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy:   0.562
              precision    recall  f1-score   support

           0       0.57      0.93      0.71      2076
           1       0.46      0.08      0.13      1581

    accuracy                           0.56      3657
   macro avg       0.51      0.50      0.42      3657
weighted avg       0.52      0.56      0.46      3657

confusion matrix:
[[1936  140]
 [1462  119]]


In [ ]:
clf = PassiveAggressiveClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


# compute the performance measures
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)

print(metrics.classification_report(y_test, y_pred))

print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))

accuracy:   0.456
              precision    recall  f1-score   support

           0       0.55      0.23      0.32      2076
           1       0.43      0.75      0.55      1581

    accuracy                           0.46      3657
   macro avg       0.49      0.49      0.43      3657
weighted avg       0.50      0.46      0.42      3657

confusion matrix:
[[ 478 1598]
 [ 390 1191]]


---------------Machine Learning Approaches End--------------------------


LSTM on tokenized text


In [ ]:
max_features=4500

In [ ]:
from nltk.tokenize import sent_tokenize,word_tokenize
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
X = df['text']

In [ ]:
tokenizer = Tokenizer(num_words = max_features, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower = True, split = ' ')
tokenizer.fit_on_texts(texts = X)
X = tokenizer.texts_to_sequences(texts = X)

In [ ]:
X = pad_sequences(sequences = X, maxlen = max_features, padding = 'pre')

In [ ]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
lstm_model = Sequential(name = 'lstm_nn_model')
lstm_model.add(layer = Embedding(input_dim = max_features, output_dim = 120, name = '1st_layer'))
lstm_model.add(layer = LSTM(units = 120, dropout = 0.2, recurrent_dropout = 0.2, name = '2nd_layer'))
lstm_model.add(layer = Dropout(rate = 0.5, name = '3rd_layer'))
lstm_model.add(layer = Dense(units = 120,  activation = 'relu', name = '4th_layer'))
lstm_model.add(layer = Dropout(rate = 0.5, name = '5th_layer'))
lstm_model.add(layer = Dense(units = len(set(y)),  activation = 'sigmoid', name = 'output_layer'))
# compiling the model
lstm_model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
lstm_model_fit = lstm_model.fit(X_train1, y_train1, epochs = 1)

383/383 [==============================] - 5663s 15s/step - loss: 0.3290 - accuracy: 0.8531


In [ ]:
y_pred = lstm_model_fit.predict(X_test1)
score1 = metrics.accuracy_score(y_test1, y_pred)
print("accuracy:   %0.3f" % score1)
print(metrics.classification_report(y_test1, y_pred))
print("confusion matrix:")
print(metrics.confusion_matrix(y_test1, y_pred))

GRU

In [ ]:
gru_model = Sequential(name = 'gru_nn_model')
gru_model.add(layer = Embedding(input_dim = max_features, output_dim = 120, name = '1st_layer'))
gru_model.add(layer = GRU(units = 120, dropout = 0.2, 
                          recurrent_dropout = 0.2, recurrent_activation = 'relu', 
                          activation = 'relu', name = '2nd_layer'))
gru_model.add(layer = Dropout(rate = 0.4, name = '3rd_layer'))
gru_model.add(layer = Dense(units = 120, activation = 'relu', name = '4th_layer'))
gru_model.add(layer = Dropout(rate = 0.2, name = '5th_layer'))
gru_model.add(layer = Dense(units = len(set(y)), activation = 'softmax', name = 'output_layer'))
# compiling the model
gru_model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
gru = gru_model.fit(X_train, y_train, epochs = 1)

In [ ]:
y_pred = gru.predict(X_test)
score1 = metrics.accuracy_score(y_test, y_pred)
print("accuracy:   %0.3f" % score1)
print(metrics.classification_report(y_test, y_pred))
print("confusion matrix:")
print(metrics.confusion_matrix(y_test, y_pred))